services:
  portfolio_site_landing:
    container_name: portfolio_site_landing
    restart: "no"
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - global_portfolio_site_network

networks:
  global_portfolio_site_network:
    external: true
