services:
  portfolio_site_landing:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      NUXT_PUBLIC_BACKEND_URL: ${NUXT_PUBLIC_BACKEND_URL_DOCKER}
      TZ: ${TZ}
    expose:
      - "3000"
